name = "homeshopview"
main = "src/worker.js"
compatibility_date = "2026-05-20"
compatibility_flags = ["nodejs_compat"]
routes = [
  { pattern = "homeshopview.com/*", zone_name = "homeshopview.com" },
  { pattern = "www.homeshopview.com/*", zone_name = "homeshopview.com" },
  { pattern = "preview.homeshopview.com/*", zone_name = "homeshopview.com" }
]

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "homeshopview-db"
database_id = "2cd638ba-3e27-4f0f-ad7a-206390085d14"

[vars]
SITE_URL = "https://homeshopview.com"
SITE_NAME = "홈쇼핑뷰 공영홈쇼핑"

[triggers]
crons = ["0 15 * * *"]
